### ISSUE TITLE
Cannot build a workspace on README.md

### ISSUE THREAD

**Issue by sktometometo** [knorth55/coral_usb_ros#1]
I had tried to build the package following the instruction in README.md, but "catkin build" command had failed because "catkin_pkg" was not found during "catkin_tools_prebuild" process.

```shell
sktometometo@Sherman ~/ros/ws_tpu_development/src [gitbranch:] [workspace:] ->
 06:28 午後 日  9月 15$ catkin clean

[clean] Warning: This will completely remove the following directories. (Use `--yes` to skip this check)
[clean] Log Space:     /home/sktometometo/ros/ws_tpu_development/logs
[clean] Build Space:   /home/sktometometo/ros/ws_tpu_development/build
[clean] Devel Space:   /home/sktometometo/ros/ws_tpu_development/devel

[clean] Are you sure you want to completely remove the directories listed above? [yN]: y
[clean] Removing develspace: /home/sktometometo/ros/ws_tpu_development/devel
[clean] Removing buildspace: /home/sktometometo/ros/ws_tpu_development/build
[clean] Removing log space: /home/sktometometo/ros/ws_tpu_development/logs
sktometometo@Sherman ~/ros/ws_tpu_development/src [gitbranch:] [workspace:] ->
 06:28 午後 日  9月 15$ cd ..
sktometometo@Sherman ~/ros/ws_tpu_development [gitbranch:] [workspace:] ->
 06:28 午後 日  9月 15$ ls
src
sktometometo@Sherman ~/ros/ws_tpu_development [gitbranch:] [workspace:] ->
 06:28 午後 日  9月 15$ ls -a
.  ..  .catkin_tools  src
sktometometo@Sherman ~/ros/ws_tpu_development [gitbranch:] [workspace:] ->
 06:28 午後 日  9月 15$ rm -rf .catkin_tools/
sktometometo@Sherman ~/ros/ws_tpu_development [gitbranch:] [workspace:] ->
 06:28 午後 日  9月 15$ catkin init
Initializing catkin workspace in `/home/sktometometo/ros/ws_tpu_development`.
------------------------------------------------------------------------------
Profile:                     default
Extending:             [env] /opt/ros/kinetic
Workspace:                   /home/sktometometo/ros/ws_tpu_development
------------------------------------------------------------------------------
Build Space:       [missing] /home/sktometometo/ros/ws_tpu_development/build
Devel Space:       [missing] /home/sktometometo/ros/ws_tpu_development/devel
Install Space:      [unused] /home/sktometometo/ros/ws_tpu_development/install
Log Space:         [missing] /home/sktometometo/ros/ws_tpu_development/logs
Source Space:       [exists] /home/sktometometo/ros/ws_tpu_development/src
DESTDIR:            [unused] None
------------------------------------------------------------------------------
Devel Space Layout:          linked
Install Space Layout:        None
------------------------------------------------------------------------------
Additional CMake Args:       None
Additional Make Args:        None
Additional catkin Make Args: None
Internal Make Job Server:    True
Cache Job Environments:      False
------------------------------------------------------------------------------
Whitelisted Packages:        None
Blacklisted Packages:        None
------------------------------------------------------------------------------
Workspace configuration appears valid.
------------------------------------------------------------------------------
sktometometo@Sherman ~/ros/ws_tpu_development [gitbranch:] [workspace:] ->
 06:28 午後 日  9月 15$ catkin config -DPYTHON_EXECUTABLE=/usr/bin/python3 -DPYTHON_INCLUDE_DIR=/usr/include/python3.5m -DPYTHON_LIBRARY=/usr/lib/x86_64-linux-gnu/libpython3.5m.so
---------------------------------------------------------------------------------------------------------
Profile:                     default
Extending:             [env] /opt/ros/kinetic
Workspace:                   /home/sktometometo/ros/ws_tpu_development
---------------------------------------------------------------------------------------------------------
Build Space:       [missing] /home/sktometometo/ros/ws_tpu_development/build
Devel Space:       [missing] /home/sktometometo/ros/ws_tpu_development/devel
Install Space:      [unused] /home/sktometometo/ros/ws_tpu_development/install
Log Space:         [missing] /home/sktometometo/ros/ws_tpu_development/logs
Source Space:       [exists] /home/sktometometo/ros/ws_tpu_development/src
DESTDIR:            [unused] None
---------------------------------------------------------------------------------------------------------
Devel Space Layout:          linked
Install Space Layout:        None
---------------------------------------------------------------------------------------------------------
Additional CMake Args:       -DPYTHON_EXECUTABLE=/usr/bin/python3 -DPYTHON_INCLUDE_DIR=/usr/include/python3.5m -DPYTHON_LIBRARY=/usr/lib/x86_64-linux-gnu/libpython3.5m.so
Additional Make Args:        None
Additional catkin Make Args: None
Internal Make Job Server:    True
Cache Job Environments:      False
---------------------------------------------------------------------------------------------------------
Whitelisted Packages:        None
Blacklisted Packages:        None
---------------------------------------------------------------------------------------------------------
Workspace configuration appears valid.
---------------------------------------------------------------------------------------------------------
sktometometo@Sherman ~/ros/ws_tpu_development [gitbranch:] [workspace:] ->
 06:28 午後 日  9月 15$ catkin build --this
[build] Error: In order to use --this, the current directory must be part of a catkin package.
sktometometo@Sherman ~/ros/ws_tpu_development [gitbranch:] [workspace:] ->
 06:28 午後 日  9月 15$ catkin build
---------------------------------------------------------------------------------------------------------
Profile:                     default
Extending:             [env] /opt/ros/kinetic
Workspace:                   /home/sktometometo/ros/ws_tpu_development
---------------------------------------------------------------------------------------------------------
Build Space:        [exists] /home/sktometometo/ros/ws_tpu_development/build
Devel Space:        [exists] /home/sktometometo/ros/ws_tpu_development/devel
Install Space:      [unused] /home/sktometometo/ros/ws_tpu_development/install
Log Space:         [missing] /home/sktometometo/ros/ws_tpu_development/logs
Source Space:       [exists] /home/sktometometo/ros/ws_tpu_development/src
DESTDIR:            [unused] None
---------------------------------------------------------------------------------------------------------
Devel Space Layout:          linked
Install Space Layout:        None
---------------------------------------------------------------------------------------------------------
Additional CMake Args:       -DPYTHON_EXECUTABLE=/usr/bin/python3 -DPYTHON_INCLUDE_DIR=/usr/include/python3.5m -DPYTHON_LIBRARY=/usr/lib/x86_64-linux-gnu/libpython3.5m.so
Additional Make Args:        None
Additional catkin Make Args: None
Internal Make Job Server:    True
Cache Job Environments:      False
---------------------------------------------------------------------------------------------------------
Whitelisted Packages:        None
Blacklisted Packages:        None
---------------------------------------------------------------------------------------------------------
Workspace configuration appears valid.

NOTE: Forcing CMake to run for each package.
---------------------------------------------------------------------------------------------------------
[build] Found '10' packages in 0.0 seconds.                                                             
[build] Updating package table.                                                                         
Starting  >>> catkin_tools_prebuild                                                                     
________________________________________________________________________________________________________
Errors     << catkin_tools_prebuild:cmake /home/sktometometo/ros/ws_tpu_development/logs/catkin_tools_prebuild/build.cmake.000.log
ImportError: "from catkin_pkg.package import parse_package" failed: No module named 'catkin_pkg'
Make sure that you have installed "catkin_pkg", it is up to date and on the PYTHONPATH.
CMake Error at /opt/ros/kinetic/share/catkin/cmake/safe_execute_process.cmake:11 (message):
  execute_process(/usr/bin/python3
  "/opt/ros/kinetic/share/catkin/cmake/parse_package_xml.py"
  "/opt/ros/kinetic/share/catkin/cmake/../package.xml"
  "/home/sktometometo/ros/ws_tpu_development/build/catkin_tools_prebuild/catkin/catkin_generated/version/package.cmake")
  returned error code 1
Call Stack (most recent call first):
  /opt/ros/kinetic/share/catkin/cmake/catkin_package_xml.cmake:74 (safe_execute_process)
  /opt/ros/kinetic/share/catkin/cmake/all.cmake:167 (_catkin_package_xml)
  /opt/ros/kinetic/share/catkin/cmake/catkinConfig.cmake:20 (include)
  CMakeLists.txt:4 (find_package)


cd /home/sktometometo/ros/ws_tpu_development/build/catkin_tools_prebuild; catkin build --get-env catkin_tools_prebuild | catkin env -si  /usr/bin/cmake /home/sktometometo/ros/ws_tpu_development/build/catkin_tools_prebuild --no-warn-unused-cli -DCATKIN_DEVEL_PREFIX=/home/sktometometo/ros/ws_tpu_development/devel/.private/catkin_tools_prebuild -DCMAKE_INSTALL_PREFIX=/home/sktometometo/ros/ws_tpu_development/install -DPYTHON_EXECUTABLE=/usr/bin/python3 -DPYTHON_INCLUDE_DIR=/usr/include/python3.5m -DPYTHON_LIBRARY=/usr/lib/x86_64-linux-gnu/libpython3.5m.so; cd -
........................................................................................................
Failed     << catkin_tools_prebuild:cmake                        [ Exited with code 1 ]                 
Failed    <<< catkin_tools_prebuild                              [ 1.4 seconds ]                        
Abandoned <<< catkin_virtualenv                                  [ Unrelated job failed ]               
Abandoned <<< cv_bridge                                          [ Unrelated job failed ]               
Abandoned <<< coral_usb                                          [ Unrelated job failed ]               
Abandoned <<< image_geometry                                     [ Unrelated job failed ]               
Abandoned <<< opencv_tests                                       [ Unrelated job failed ]               
Abandoned <<< test_catkin_virtualenv                             [ Unrelated job failed ]               
Abandoned <<< test_catkin_virtualenv_inherited                   [ Unrelated job failed ]               
Abandoned <<< test_catkin_virtualenv_py3                         [ Unrelated job failed ]               
Abandoned <<< test_catkin_virtualenv_py3_isolated                [ Unrelated job failed ]               
[build] Summary: 0 of 10 packages succeeded.                                                            
[build]   Ignored:   1 packages were skipped or are blacklisted.                                        
[build]   Warnings:  None.                                                                              
[build]   Abandoned: 9 packages were abandoned.                                                         
[build]   Failed:    1 packages failed.                                                                 
[build] Runtime: 1.5 seconds total.    
```

I suspect that this is because python3-catkin-pkg package is not installed in my computer and python3 environment in my pc cannot use catkin_pkg python module, but the python3-catkin-pkg debian package for ubuntu conflicts with python-catkin-pkg, and if I install python3-catkin-pkg package to my pc, my ROS environment will break.

```
sktometometo@Sherman ~ [gitbranch:] [workspace:] ->
 06:45 PM Sun Sep 15$ apt show python3-catkin-pkg
Package: python3-catkin-pkg
Version: 0.4.13-100
Priority: optional
Section: python
Maintainer: Dirk Thomas <dthomas@osrfoundation.org>
Installed-Size: 25.6 kB
Depends: python3-dateutil, python3-docutils, python3-pyparsing, python3:any (>= 3.4~), python3-catkin-pkg-modules (>= 0.4.13)
Conflicts: catkin, python-catkin-pkg
Homepage: http://wiki.ros.org/catkin_pkg
Download-Size: 3508 B
APT-Sources: http://packages.ros.org/ros/ubuntu xenial/main amd64 Packages
Description: catkin package library
 Library for retrieving information about catkin packages.

sktometometo@Sherman ~ [gitbranch:] [workspace:] ->
 06:45 PM Sun Sep 15$ sudo apt install python3-catkin-pkg
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  festival festlex-cmu festlex-poslex festvox-kallpc16k fltk1.3-doc fluid gazebo7 gazebo7-common
  gazebo7-plugin-base google-mock hddtemp hdf5-helpers libaec-dev libapr1-dev libaprutil1-dev
  libarmadillo6 libarpack2 libassimp-dev libassimp3v5 libbullet-dev libbulletcollision2.83.6
  libbulletdynamics2.83.6 libbulletsoftbody2.83.6 libbz2-dev libcollada-dom2.4-dp-dev
  libcollada-dom2.4-dp0 libconsole-bridge-dev libconsole-bridge0.2v5 libcurl4-openssl-dev libdap-dev
  libdap17v5 libdapclient6v5 libdapserver7v5 libepsilon1 libestools2.4 libflann-dev libflann1.8
  libfltk-cairo1.3 libfltk-forms1.3 libfltk-gl1.3 libfltk-images1.3 libfltk1.3 libfltk1.3-dev
  libfreeimage-dev libfreexl1 libgazebo7 libgazebo7-dev libgdal-dev libgdal1i libgeos-3.5.0
  libgeos-c1v5 libgeos-dev libgif-dev libgl2ps-dev libgl2ps0 libgles2-mesa-dev libgtest-dev
  libgts-0.7-5 libgts-bin libgts-dev libhdf4-0-alt libhdf4-alt-dev libhdf5-cpp-11 libhdf5-dev
  libhdf5-mpi-dev libhdf5-openmpi-10 libhdf5-openmpi-dev libignition-math2 libignition-math2-dev
  libinput-dev libjsoncpp-dev libkmlbase1 libkmldom1 libkmlengine1 libldap2-dev liblinearmath2.83.6
  liblog4cxx-dev liblog4cxx10-dev liblog4cxx10v5 liblz4-dev libminizip1 libnetcdf-c++4
  libnetcdf-cxx-legacy-dev libnetcdf-dev libnetcdf11 libogdi3.2 libogg-dev libogre-1.9-dev
  libogre-1.9.0v5 libopenni-dev libopenni-sensor-pointclouds0 libopenni0 libopenni2-0 libopenni2-dev
  libpcl-apps1.7 libpcl-common1.7 libpcl-dev libpcl-features1.7 libpcl-filters1.7 libpcl-io1.7
  libpcl-kdtree1.7 libpcl-keypoints1.7 libpcl-octree1.7 libpcl-outofcore1.7 libpcl-people1.7
  libpcl-recognition1.7 libpcl-registration1.7 libpcl-sample-consensus1.7 libpcl-search1.7
  libpcl-segmentation1.7 libpcl-surface1.7 libpcl-tracking1.7 libpcl-visualization1.7 libpcl1.7
  libpoco-dev libpococrypto9v5 libpocodata9v5 libpocofoundation9v5 libpocomysql9v5 libpoconet9v5
  libpoconetssl9v5 libpocoodbc9v5 libpocosqlite9v5 libpocoutil9v5 libpocoxml9v5 libpocozip9v5 libproj9
  libpyside-py3-2.0 libpyside2-dev libpyside2.0 libqgsttools-p1 libqhull-dev libqhull7 libqt5clucene5
  libqt5concurrent5 libqt5designer5 libqt5designercomponents5 libqt5help5 libqt5multimediaquick-p5
  libqt5multimediawidgets5 libqt5opengl5-dev libqt5quickparticles5 libqt5quickwidgets5 libqt5script5
  libqt5scripttools5 libqt5svg5-dev libqt5webkit5-dev libqt5x11extras5-dev libqt5xmlpatterns5
  libqt5xmlpatterns5-dev libqt5xmlpatterns5-private-dev libqtwebkit-dev libsctp-dev libsctp1
  libsdformat4 libsdformat4-dev libshiboken-py3-2.0 libshiboken2-dev libshiboken2.0 libsimbody-dev
  libsimbody3.5v5 libspatialite-dev libspatialite7 libspnav0 libsuperlu4 libtar-dev libtar0 libtbb-dev
  libtheora-dev libtinyxml-dev libtinyxml2-2v5 libtinyxml2-dev libudev-dev liburdfdom-dev
  liburdfdom-headers-dev liburdfdom-model-state0.4 liburdfdom-model0.4 liburdfdom-sensor0.4
  liburdfdom-tools liburdfdom-world0.4 liburiparser1 libusb-1.0-0-dev libusb-1.0-doc libvtk6-dev
  libvtk6-java libvtk6-qt-dev libvtk6.2 libvtk6.2-qt libxerces-c-dev libxerces-c3.1 libxss-dev
  libyaml-cpp-dev libyaml-cpp0.5v5 openni-utils proj-bin proj-data pyqt5-dev python-attr
  python-autobahn python-catkin-pkg-modules python-concurrent.futures python-defusedxml python-empy
  python-lz4 python-mpi4py python-msgpack python-netifaces python-opengl python-osrf-pycommon
  python-pam python-psutil python-pyasn1-modules python-pydot python-pyqt5 python-pyqt5.qtopengl
  python-pyqt5.qtsvg python-pyqt5.qtwebkit python-pyside2 python-pyside2.qtconcurrent
  python-pyside2.qtcore python-pyside2.qtgui python-pyside2.qthelp python-pyside2.qtnetwork
  python-pyside2.qtprintsupport python-pyside2.qtqml python-pyside2.qtquick
  python-pyside2.qtquickwidgets python-pyside2.qtscript python-pyside2.qtsql python-pyside2.qtsvg
  python-pyside2.qttest python-pyside2.qtuitools python-pyside2.qtwebkit python-pyside2.qtwebkitwidgets
  python-pyside2.qtwidgets python-pyside2.qtx11extras python-pyside2.qtxml python-rosdistro
  python-rosdistro-modules python-rospkg python-rospkg-modules python-serial python-service-identity
  python-sip-dev python-snappy python-trollius python-twisted python-twisted-bin python-twisted-core
  python-txaio python-vtk6 python-wxtools qt5-qmake qtbase5-dev qtbase5-dev-tools qtbase5-private-dev
  qtdeclarative5-dev qtdeclarative5-private-dev qtmultimedia5-dev qtscript5-dev qtscript5-private-dev
  qttools5-dev qttools5-dev-tools qttools5-private-dev ros-kinetic-angles ros-kinetic-class-loader
  ros-kinetic-cmake-modules ros-kinetic-cpp-common ros-kinetic-eigen-stl-containers
  ros-kinetic-gazebo-dev ros-kinetic-gl-dependency ros-kinetic-libcmt ros-kinetic-libsiftfast
  ros-kinetic-media-export ros-kinetic-python-qt-binding ros-kinetic-qt-dotgraph ros-kinetic-qt-gui
  ros-kinetic-qt-gui-py-common ros-kinetic-qwt-dependency ros-kinetic-random-numbers
  ros-kinetic-ros-environment ros-kinetic-rosbag-migration-rule ros-kinetic-rosbag-storage
  ros-kinetic-rosboost-cfg ros-kinetic-rosclean ros-kinetic-roscpp-core
  ros-kinetic-roscpp-serialization ros-kinetic-roscpp-traits ros-kinetic-rosgraph ros-kinetic-roslint
  ros-kinetic-roslz4 ros-kinetic-rosmaster ros-kinetic-rosparam ros-kinetic-rostime ros-kinetic-smclib
  ros-kinetic-urdf-parser-plugin ros-kinetic-webkit-dependency ros-kinetic-xmlrpcpp sbcl sdformat-sdf
  shiboken2 sip-dev spacenavd tango-icon-theme tcl-dev tcl-vtk6 tcl8.6-dev tk-dev tk8.6-dev
  ttf-dejavu-core uuid-dev vtk6 x11proto-scrnsaver-dev
Use 'sudo apt autoremove' to remove them.
The following additional packages will be installed:
  python3-catkin-pkg-modules
The following packages will be REMOVED:
  python-catkin-pkg python-catkin-tools python-rosdep ros-kinetic-actionlib ros-kinetic-actionlib-msgs
  ros-kinetic-actionlib-tutorials ros-kinetic-audio-common-msgs ros-kinetic-bond ros-kinetic-bond-core
  ros-kinetic-bondcpp ros-kinetic-bondpy ros-kinetic-camera-calibration
  ros-kinetic-camera-calibration-parsers ros-kinetic-camera-info-manager ros-kinetic-catkin
  ros-kinetic-collada-parser ros-kinetic-collada-urdf ros-kinetic-common-msgs
  ros-kinetic-common-tutorials ros-kinetic-compressed-depth-image-transport
  ros-kinetic-compressed-image-transport ros-kinetic-control-msgs ros-kinetic-cv-bridge
  ros-kinetic-depth-image-proc ros-kinetic-desktop ros-kinetic-desktop-full
  ros-kinetic-diagnostic-aggregator ros-kinetic-diagnostic-analysis
  ros-kinetic-diagnostic-common-diagnostics ros-kinetic-diagnostic-msgs ros-kinetic-diagnostic-updater
  ros-kinetic-diagnostics ros-kinetic-dynamic-reconfigure ros-kinetic-dynamic-tf-publisher
  ros-kinetic-eigen-conversions ros-kinetic-executive-smach ros-kinetic-filters ros-kinetic-gazebo-msgs
  ros-kinetic-gazebo-plugins ros-kinetic-gazebo-ros ros-kinetic-gazebo-ros-pkgs ros-kinetic-gencpp
  ros-kinetic-geneus ros-kinetic-genlisp ros-kinetic-genmsg ros-kinetic-gennodejs ros-kinetic-genpy
  ros-kinetic-geometric-shapes ros-kinetic-geometry ros-kinetic-geometry-msgs
  ros-kinetic-geometry-tutorials ros-kinetic-image-common ros-kinetic-image-geometry
  ros-kinetic-image-pipeline ros-kinetic-image-proc ros-kinetic-image-publisher
  ros-kinetic-image-rotate ros-kinetic-image-transport ros-kinetic-image-transport-plugins
  ros-kinetic-image-view ros-kinetic-image-view2 ros-kinetic-imagesift
  ros-kinetic-interactive-marker-tutorials ros-kinetic-interactive-markers
  ros-kinetic-joint-state-publisher ros-kinetic-jsk-data ros-kinetic-jsk-footstep-msgs
  ros-kinetic-jsk-gui-msgs ros-kinetic-jsk-perception ros-kinetic-jsk-recognition-msgs
  ros-kinetic-jsk-recognition-utils ros-kinetic-jsk-topic-tools ros-kinetic-kdl-conversions
  ros-kinetic-kdl-parser ros-kinetic-laser-assembler ros-kinetic-laser-filters
  ros-kinetic-laser-geometry ros-kinetic-laser-pipeline ros-kinetic-librviz-tutorial
  ros-kinetic-map-msgs ros-kinetic-message-filters ros-kinetic-message-generation
  ros-kinetic-message-runtime ros-kinetic-mk ros-kinetic-nav-msgs ros-kinetic-nodelet
  ros-kinetic-nodelet-core ros-kinetic-nodelet-topic-tools ros-kinetic-nodelet-tutorial-math
  ros-kinetic-octomap ros-kinetic-opencv-apps ros-kinetic-opencv3 ros-kinetic-openni-camera
  ros-kinetic-openni-launch ros-kinetic-openni2-camera ros-kinetic-openni2-launch
  ros-kinetic-orocos-kdl ros-kinetic-pcl-conversions ros-kinetic-pcl-msgs ros-kinetic-pcl-ros
  ros-kinetic-perception ros-kinetic-perception-pcl ros-kinetic-pluginlib
  ros-kinetic-pluginlib-tutorials ros-kinetic-polled-camera ros-kinetic-posedetection-msgs
  ros-kinetic-pr2-description ros-kinetic-python-orocos-kdl ros-kinetic-qt-gui-cpp
  ros-kinetic-resource-retriever ros-kinetic-rgbd-launch ros-kinetic-robot ros-kinetic-robot-model
  ros-kinetic-robot-self-filter ros-kinetic-robot-state-publisher ros-kinetic-ros ros-kinetic-ros-base
  ros-kinetic-ros-comm ros-kinetic-ros-core ros-kinetic-ros-tutorials ros-kinetic-rosbag
  ros-kinetic-rosbash ros-kinetic-rosbuild ros-kinetic-rosconsole ros-kinetic-rosconsole-bridge
  ros-kinetic-roscpp ros-kinetic-roscpp-tutorials ros-kinetic-roscreate ros-kinetic-roseus
  ros-kinetic-rosgraph-msgs ros-kinetic-roslang ros-kinetic-roslaunch ros-kinetic-roslib
  ros-kinetic-roslisp ros-kinetic-rosmake ros-kinetic-rosmsg ros-kinetic-rosnode ros-kinetic-rosout
  ros-kinetic-rospack ros-kinetic-rospy ros-kinetic-rospy-tutorials ros-kinetic-rosservice
  ros-kinetic-rostest ros-kinetic-rostopic ros-kinetic-rosunit ros-kinetic-roswtf
  ros-kinetic-rqt-action ros-kinetic-rqt-bag ros-kinetic-rqt-bag-plugins ros-kinetic-rqt-common-plugins
  ros-kinetic-rqt-console ros-kinetic-rqt-dep ros-kinetic-rqt-graph ros-kinetic-rqt-gui
  ros-kinetic-rqt-gui-cpp ros-kinetic-rqt-gui-py ros-kinetic-rqt-image-view ros-kinetic-rqt-launch
  ros-kinetic-rqt-logger-level ros-kinetic-rqt-moveit ros-kinetic-rqt-msg ros-kinetic-rqt-nav-view
  ros-kinetic-rqt-plot ros-kinetic-rqt-pose-view ros-kinetic-rqt-publisher ros-kinetic-rqt-py-common
  ros-kinetic-rqt-py-console ros-kinetic-rqt-reconfigure ros-kinetic-rqt-robot-dashboard
  ros-kinetic-rqt-robot-monitor ros-kinetic-rqt-robot-plugins ros-kinetic-rqt-robot-steering
  ros-kinetic-rqt-runtime-monitor ros-kinetic-rqt-rviz ros-kinetic-rqt-service-caller
  ros-kinetic-rqt-shell ros-kinetic-rqt-srv ros-kinetic-rqt-tf-tree ros-kinetic-rqt-top
  ros-kinetic-rqt-topic ros-kinetic-rqt-web ros-kinetic-rviz ros-kinetic-rviz-plugin-tutorials
  ros-kinetic-rviz-python-tutorial ros-kinetic-self-test ros-kinetic-sensor-msgs ros-kinetic-shape-msgs
  ros-kinetic-simulators ros-kinetic-smach-msgs ros-kinetic-smach-ros ros-kinetic-sound-play
  ros-kinetic-stage ros-kinetic-stage-ros ros-kinetic-std-msgs ros-kinetic-std-srvs
  ros-kinetic-stereo-image-proc ros-kinetic-stereo-msgs ros-kinetic-tf ros-kinetic-tf-conversions
  ros-kinetic-tf2 ros-kinetic-tf2-eigen ros-kinetic-tf2-geometry-msgs ros-kinetic-tf2-kdl
  ros-kinetic-tf2-msgs ros-kinetic-tf2-py ros-kinetic-tf2-ros ros-kinetic-theora-image-transport
  ros-kinetic-topic-tools ros-kinetic-trajectory-msgs ros-kinetic-turtle-actionlib
  ros-kinetic-turtle-tf ros-kinetic-turtle-tf2 ros-kinetic-turtlesim ros-kinetic-urdf
  ros-kinetic-urdf-tutorial ros-kinetic-vision-opencv ros-kinetic-visualization-marker-tutorials
  ros-kinetic-visualization-msgs ros-kinetic-visualization-tutorials ros-kinetic-viz ros-kinetic-xacro
The following NEW packages will be installed:
  python3-catkin-pkg python3-catkin-pkg-modules
0 upgraded, 2 newly installed, 221 to remove and 3 not upgraded.
Need to get 0 B/44.8 kB of archives.
After this operation, 389 MB disk space will be freed.
Do you want to continue? [Y/n] n
Abort.
```

Is there any way to build this package? Should I build python3-catkin-pkg from source?

**Comment by knorth55** [comment]
please try this command `sudo apt install python3-catkin-pkg-modules`
https://stackoverflow.com/questions/49221565/unable-to-use-cv-bridge-with-ros-kinetic-and-python3

**Comment by sktometometo** [comment]
I have successfully build this package, thank you!
I have created a pull request about python3-<hoge>-modules dependencies. Please check [this](https://github.com/knorth55/coral_usb_ros/pull/4).

And I have got another error with sample launch.

```bash
sktometometo@Sherman ~ [gitbranch:] [workspace:/home/sktometometo/ros/ws_tpu_development] ->
 09:51 午後 日  9月 15$ roslaunch coral_usb edgetpu_object_detector.launch INPUT_IMAGE:=/image_publisher/output
... logging to /home/sktometometo/.ros/log/e2b568ee-d7b6-11e9-9339-507b9daced47/roslaunch-Sherman-16564.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://Sherman:38553/

SUMMARY
========

PARAMETERS
 * /rosdistro: kinetic
 * /rosversion: 1.12.14

NODES
  /
    edgetpu_object_detector (coral_usb/edgetpu_object_detector.py)

ROS_MASTER_URI=http://localhost:11311

process[edgetpu_object_detector-1]: started with pid [16582]
Traceback (most recent call last):
  File "/home/sktometometo/ros/ws_tpu_development/src/coral_usb_ros/node_scripts/edgetpu_object_detector.py", line 17, in <module>
    from chainercv.visualizations import vis_bbox
ImportError: No module named 'chainercv'
[edgetpu_object_detector-1] process has died [pid 16582, exit code 1, cmd /home/sktometometo/ros/ws_tpu_development/devel/lib/coral_usb/edgetpu_object_detector.py ~input:=/image_publisher/output __name:=edgetpu_object_detector __log:=/home/sktometometo/.ros/log/e2b568ee-d7b6-11e9-9339-507b9daced47/edgetpu_object_detector-1.log].
log file: /home/sktometometo/.ros/log/e2b568ee-d7b6-11e9-9339-507b9daced47/edgetpu_object_detector-1*.log
[edgetpu_object_detector-1] restarting process
process[edgetpu_object_detector-1]: started with pid [16588]
Traceback (most recent call last):
  File "/home/sktometometo/ros/ws_tpu_development/src/coral_usb_ros/node_scripts/edgetpu_object_detector.py", line 17, in <module>
    from chainercv.visualizations import vis_bbox
ImportError: No module named 'chainercv'
[edgetpu_object_detector-1] process has died [pid 16588, exit code 1, cmd /home/sktometometo/ros/ws_tpu_development/devel/lib/coral_usb/edgetpu_object_detector.py ~input:=/image_publisher/output __name:=edgetpu_object_detector __log:=/home/sktometometo/.ros/log/e2b568ee-d7b6-11e9-9339-507b9daced47/edgetpu_object_detector-1.log].
log file: /home/sktometometo/.ros/log/e2b568ee-d7b6-11e9-9339-507b9daced47/edgetpu_object_detector-1*.log
[edgetpu_object_detector-1] restarting process
process[edgetpu_object_detector-1]: started with pid [16594]
^C[edgetpu_object_detector-1] killing on exit
ImportError: numpy.core.multiarray failed to import
Traceback (most recent call last):
  File "/home/sktometometo/ros/ws_tpu_development/src/coral_usb_ros/node_scripts/edgetpu_object_detector.py", line 14, in <module>
    import cv2  # NOQA
ImportError: numpy.core.multiarray failed to import
shutting down processing monitor...
... shutting down processing monitor complete
done
```

This seemed because python3 environment did not have chainercv modules. and this error did not appear after instaling chainercv to python3 environment with pip3 command.
Is there any way to mark python3 library dependencies in catkin package.xml?


In addition, I have still got an error while executing the launch after chainercv installation to python3.

```bash
sktometometo@Sherman ~ [gitbranch:] [workspace:/home/sktometometo/ros/ws_tpu_development] ->
 09:54 午後 日  9月 15$ roslaunch coral_usb edgetpu_object_detector.launch INPUT_IMAGE:=/image_publisher/output
... logging to /home/sktometometo/.ros/log/e2b568ee-d7b6-11e9-9339-507b9daced47/roslaunch-Sherman-17864.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://Sherman:41065/

SUMMARY
========

PARAMETERS
 * /rosdistro: kinetic
 * /rosversion: 1.12.14

NODES
  /
    edgetpu_object_detector (coral_usb/edgetpu_object_detector.py)

ROS_MASTER_URI=http://localhost:11311

process[edgetpu_object_detector-1]: started with pid [17881]
Traceback (most recent call last):
  File "/home/sktometometo/ros/ws_tpu_development/src/coral_usb_ros/node_scripts/edgetpu_object_detector.py", line 28, in <module>
    from jsk_topic_tools import ConnectionBasedTransport
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/jsk_topic_tools/__init__.py", line 5, in <module>
    from .log_utils import *
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/jsk_topic_tools/log_utils.py", line 4, in <module>
    import cPickle as pickle
ImportError: No module named 'cPickle'
[edgetpu_object_detector-1] process has died [pid 17881, exit code 1, cmd /home/sktometometo/ros/ws_tpu_development/devel/lib/coral_usb/edgetpu_object_detector.py ~input:=/image_publisher/output __name:=edgetpu_object_detector __log:=/home/sktometometo/.ros/log/e2b568ee-d7b6-11e9-9339-507b9daced47/edgetpu_object_detector-1.log].
log file: /home/sktometometo/.ros/log/e2b568ee-d7b6-11e9-9339-507b9daced47/edgetpu_object_detector-1*.log
[edgetpu_object_detector-1] restarting process
process[edgetpu_object_detector-1]: started with pid [17892]
Traceback (most recent call last):
  File "/home/sktometometo/ros/ws_tpu_development/src/coral_usb_ros/node_scripts/edgetpu_object_detector.py", line 28, in <module>
    from jsk_topic_tools import ConnectionBasedTransport
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/jsk_topic_tools/__init__.py", line 5, in <module>
    from .log_utils import *
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/jsk_topic_tools/log_utils.py", line 4, in <module>
    import cPickle as pickle
ImportError: No module named 'cPickle'
[edgetpu_object_detector-1] process has died [pid 17892, exit code 1, cmd /home/sktometometo/ros/ws_tpu_development/devel/lib/coral_usb/edgetpu_object_detector.py ~input:=/image_publisher/output __name:=edgetpu_object_detector __log:=/home/sktometometo/.ros/log/e2b568ee-d7b6-11e9-9339-507b9daced47/edgetpu_object_detector-1.log].
log file: /home/sktometometo/.ros/log/e2b568ee-d7b6-11e9-9339-507b9daced47/edgetpu_object_detector-1*.log
[edgetpu_object_detector-1] restarting process
process[edgetpu_object_detector-1]: started with pid [17904]
Traceback (most recent call last):
  File "/home/sktometometo/ros/ws_tpu_development/src/coral_usb_ros/node_scripts/edgetpu_object_detector.py", line 28, in <module>
    from jsk_topic_tools import ConnectionBasedTransport
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/jsk_topic_tools/__init__.py", line 5, in <module>
    from .log_utils import *
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/jsk_topic_tools/log_utils.py", line 4, in <module>
    import cPickle as pickle
ImportError: No module named 'cPickle'
^C[edgetpu_object_detector-1] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
done**
```

This seems to be related to [this pull request](https://github.com/jsk-ros-pkg/jsk_common/pull/1636).
I am trying to build the version of jsk_topic_tools.

**Comment by knorth55** [comment]
Did you do `source ~/ros/coral_ws/devel/setup.bash` before launching?

**Comment by sktometometo** [comment]
I have succecfuly run the exapmle by building jsk_topic_tools and source the workspace.
